CostsCalculator/Controllers/CategoryController.cs
using System.Linq;
using System.Web.Mvc;
using CostsCalculator.Models;
using CostsCalculator.Models.Abstract;

namespace CostsCalculator.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private IPurchasesRepositiry repository;

        public CategoryController(IPurchasesRepositiry r)
        {
            repository = r;
        }
        [HttpGet]
        public ActionResult GetAllCategories()
        {
            User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if(currUser != null)
            {
                int userId =currUser .Id;

                var categories = repository.Categories.Where(x => x.UserId == userId).ToList();

                return View(categories);
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult Edit(int categoryId)
        {
            User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if(currUser != null)
            {
                int userId =currUser .Id;

                Category category = repository.Categories.FirstOrDefault(p => p.Id == categoryId && p.UserId == userId);
                return View(category);
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult Delete(int categoryId)
        {
            if (ModelState.IsValid)
            {
                repository.DeleteCategory(categoryId);
            }
           
            return RedirectToAction("GetAllCategories");
        }

        [HttpGet]
        public ActionResult Create()
        {
            User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);

            if (currUser != null)
            {
                int userId = currUser.Id;

                Category category = new Category {UserId = userId};

                return View("Edit", category);
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {

                repository.SaveCategory(category);
                return RedirectToAction("GetAllCategories");
            }

            return View("Edit");
        }
    }
}

CostsCalculator/Controllers/PieChartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using CostsCalculator.Models;
using CostsCalculator.Models.Abstract;

namespace CostsCalculator.Controllers
{
    [Authorize]
    public class PieChartController : Controller
    {
        private IPurchasesRepositiry repository;


        public PieChartController(IPurchasesRepositiry r)
        {
            repository = r;           
        }

        public ActionResult GetDataCategory(string fromDate,string toDate,string categoryId)
        {
            User currUser = repository.Users.Where(x => x.Name == User.Identity.Name).FirstOrDefault();

            if (currUser != null)
            {
                DateTime dateFrom;
                DateTime dateTo;
                int idCategory;
                int userId =currUser .Id;
                DateTime.TryParse(fromDate, out dateFrom);
                DateTime.TryParse(toDate, out dateTo);
                int.TryParse(categoryId, out idCategory);


                var listCategories = repository.Categories.ToList();
                var purchases = repository.Purchases.Where(x => x.UserId == userId).Include(p => p.Category).ToList();

                List<CostsDataPoint> costsData;
                if (idCategory == 0)
                {
                    var dataCategories = listCategories.Select(c => new CostsDataPoint
                    {
                        Name = c.Name,
                        Value = purchases.Where(p => p.CategoryId == c.Id && p.Date >= dateFrom && p.Date <= dateTo)
                            .Sum(x => x.UnitCost * x.Amount),
                        Color = c.ColorForDiagram
                    });
                    costsData = dataCategories.ToList();
                }
                else
                {
                    var dataCategories = listCategories.Select(c => new CostsDataPoint
                    {
                        Name = c.Name,
                        Value = purchases.Where(p => p.CategoryId == c.Id && p.CategoryId == idCategory &&
                                                     p.Date >= dateFrom && p.Date <= dateTo)
                            .Sum(x => x.UnitCost * x.Amount),
                        Color = c.ColorForDiagram
                    });
                    costsData = dataCategories.ToList();
                }

                var json = Json(new {Categories = costsData}, JsonRequestBehavior.AllowGet);

                return json;
            }

            return RedirectToAction("Login", "Account");
        }

    }
}

CostsCalculator/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using CostsCalculator.Models;
using CostsCalculator.Models.Abstract;

namespace CostsCalculator.Controllers
{
    [Authorize]
    [HandleError(ExceptionType = typeof(IndexOutOfRangeException), View = "Error")]
    public class PurchaseController : Controller
    {
        private IPurchasesRepositiry repository;
        private int pageSize = 6;      

        public PurchaseController(IPurchasesRepositiry repo)
        {
            repository = repo;           
        }

        [HttpGet]
        public ActionResult Index()
        {           
            return View();
        }

        [HttpGet]
        public ActionResult FirstListPurchases()
        {
            User currentUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if (currentUser != null)
            {
                int userId = currentUser.Id;
                DateTime dateFromFirst;

                if (repository.Purchases.Any(x => x.UserId == userId))
                    dateFromFirst = repository.Purchases.Where(p => p.UserId == userId).Min(x => x.Date);
                else
                    dateFromFirst = DateTime.Now;

                return RedirectToAction("GetAllPurchases",
                    new {dateFrom = dateFromFirst.Date, dateTo = DateTime.Now.Date, page = 1, category = 0});
            }

            return RedirectToAction("Login", "Account");

        }

        [HttpGet]
        public ActionResult GetAllPurchases(DateTime dateFrom,DateTime dateTo, int page = 1, int category = 0 )
        {
            User currentUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if (currentUser != null)
            {
                IEnumerable<Purchase> purchasesList;
                var categoriesList = repository.Categories.ToList();
                int userId = currentUser.Id;

                if (category == 0)
                    purchasesList = repository.Purchases.Include(x => x.Category)
                        .Where(x => x.Date >= dateFrom && x.Date <= dateTo && x.UserId == userId)
                        .ToList();
                else
                    purchasesList = repository.Purchases
                        .Where(x => x.Date >= dateFrom && x.Date <= dateTo && x.CategoryId == category &&
                                    x.UserId == userId)
                        .ToList();

                PurchasesCollection model = new PurchasesCollection
                {
                    Purchases = purchasesList.OrderBy(x => x.Id).Skip((page - 1) * pageSize).Take(pageSize),
                    FromDate = dateFrom.Date,
                    ToDate = dateTo.Date,
                    PagingInfo = FillPagingInfo(page, purchasesList.Count())
                };

                SelectList list = ReturnSelectList(categoriesList);
                ViewBag.Categories = list;

                return View(model);
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult CalcAllCosts()
        {
            User currentUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if (currentUser != null)
            {
                int userId = currentUser.Id;
                double allCosts;

                if (repository.Purchases.Any(x => x.UserId == userId))
                    allCosts = repository.Purchases.Where(x => x.UserId == userId)
                        .Select(x => x.Amount * x.UnitCost)
                        .Sum();
                else
                    allCosts = 0;

                return PartialView(allCosts);
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult GetLatestDateOfCost()
        {
            User currentUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
            if (currentUser != null)
            {
                int userId = currentUser.Id;
                DateTime latesTime;

                if (repository.Purchases.Any(x => x.UserId == userId))
                {
                    var latestPurchase = repository.Purchases.Where(x => x.UserId == userId)
                        .Include(x => x.Category)
                        .Min(x => x.Date);
                    latesTime = latestPurchase.Date;
                }
                else
                {
                    latesTime = DateTime.Now;
                }

                return PartialView(latesTime);
            }
            return RedirectToAction("Login", "Account");
        }

        #region MODIFICATION
        [HttpDelete]
        public ActionResult Delete(int purchaseId)
        {
            User currentUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);

            if (currentUser != null)
            {
                int userId = currentUser.Id;
                if (ModelState.IsValid)
                {
                    repository.DeletePurchase(purchaseId);
                }

                DateTime dateFromFirst;
                if (repository.Purchases.Count(x => x.UserId == userId) > 0)
                    dateFromFirst = repository.Purchases.Where(x => x.UserId == userId).Min(x => x.Date);
                else
                    dateFromFirst = DateTime.Now;
                return RedirectToAction("GetAllPurchases",
                    new {dateFrom = dateFromFirst.Date, dateTo = DateTime.Now.Date, page = 1, category = 0});
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public ActionResult Edit(int purchaseId)
        {
            Purchase purchase = repository.Purchases.FirstOrDefault(p => p.Id == purchaseId);

            if (purchase != null)
            {
                SelectList list = ReturnSelectList(purchase.CategoryId);
                ViewBag.Categories = list;

                return View(purchase);
            }
            //TODO: Show error message
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);
                if (currUser != null)
                {
                    int userId = currUser.Id;

                    repository.SavePurchase(purchase);
                    DateTime dateFromFirst = repository.Purchases.Where(x => x.UserId == userId).Min(x => x.Date);

                    return RedirectToAction("GetAllPurchases",
                        new {dateFrom = dateFromFirst.Date, dateTo = DateTime.Now.Date, page = 1, category = 0});
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }

            return View("Edit");
        }

        [HttpGet]
        public ActionResult Create()
        {
            User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);

            if (currUser != null)
            {
                int userId = currUser.Id;

                Purchase purchase = new Purchase {UserId = userId, Date = DateTime.Now};

                SelectList list = ReturnSelectList(purchase.CategoryId);
                if (list == null || !list.Any())
                    return View("EmptyCategory");

                ViewBag.Categories = list;

                return View("Edit", purchase);
            }

            return RedirectToAction("Login", "Account");
        }
        #endregion



        #region FILTRATION
        [HttpGet]
        public ActionResult FilterForPeriod(string period)
        {
            DateTime toDate = DateTime.Now;
            DateTime fromDate;
            switch (period)
            {
                case "week":
                {
                    fromDate = toDate.AddDays(-7);
                    break;
                }
                case "month":
                {
                    fromDate = toDate.AddMonths(-1);
                    break;
                }
                case "year":
                {
                    fromDate = toDate.AddYears(-1);
                    break;
                }
                default:
                {
                    fromDate = toDate.AddYears(-1);
                    break;
                }
            }

            return FilterByData(fromDate, toDate);
        }

        [HttpPost]
        public ActionResult FilterByData(DateTime FromDate, DateTime ToDate , int category = 0)
        {
            User currUser = repository.Users.FirstOrDefault(x => x.Name == User.Identity.Name);

            if (currUser != null)
            {
                IEnumerable<Purchase> purchasesList;
                int userId = currUser.Id;
                var categories = repository.Categories.ToList();

                if (category == 0)
                    purchasesList = repository.Purchases.Include(x => x.Category)
                        .Where(x => x.Date >= FromDate && x.Date <= ToDate && x.UserId == userId)
                        .ToList();
                else
                    purchasesList = repository.Purchases.Include(x => x.Category)
                        .Where(x => x.Date >= FromDate && x.Date <= ToDate && x.CategoryId == category &&
                                    x.UserId == userId)
                        .ToList();



CostsCalculator/Views/Shared/DrawPieChart.cshtml
@using System.Web.Script.Serialization
@using System.Web.UI.WebControls
@using CostsCalculator.Models
@model IEnumerable<CostsCalculator.Models.Purchase>

<div id="chart_div"></div>

<script type="text/javascript">


    google.load('visualization', '1.0', { 'packages': ['corechart'] });

    // Setup callback
    google.setOnLoadCallback(drawChart);



    function drawChart() {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Category');
        data.addColumn('number', 'Slices');
        var options;
        var colorsTabel = [];
        var fromD = $('#dateFrom input:first-child').val();
        var toD = $('#dateTo input:first-child').val();
        var categoryId = $("#categoryId select[name=category] option:selected").val();
        if (categoryId == "")
            categoryId = 0;

        $.getJSON('@Url.Action("GetDataCategory", "PieChart")', { fromDate: fromD, toDate: toD, categoryId: categoryId },
            function (result) {
                console.log(result);
                if (result.Categories.length) {
                    var i = 0;                

                    $.each(result.Categories, function (index, c) {
                        data.addRow([c.Name, c.Value]);
                        colorsTabel[i] = c.Color;
                        i++;
                    });

                    @if (Model != null)
                    {
                        <text>
                        options = {
                            'width': 600,
                            'height': 400,
                            'colors': colorsTabel,
                            'chartArea': { left: 10, top: 0, width: '100%', height: '100%' },
                            'legend': { position: 'right', textStyle: { fontSize: 18 }, alignment: 'center' },
                            'titleTextStyle': { fontSize: 20, bold: false }
                        };
                        </text>
                    }
                    else
                    {
                        <text>
                            options = {
                                'width': 900,
                                'height': 600,
                                'colors': colorsTabel,
                                'chartArea': { left: 20, top: 0, width: '100%', height: '100%' },
                                'legend': { position: 'right', textStyle: { fontSize: 18 }, alignment: 'center' },
                                'titleTextStyle': { fontSize: 20, bold: false },
                            };
                        </text>
                    }
                    

                    // Draw chart
                    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                    chart.draw(data, options);

                };
            });

    }

    function drawChartData() {

        @{
                    if (Model != null)
                    {
                        Dictionary<int, CostsDataPoint> costsByCategories = new Dictionary<int, CostsDataPoint>();


                        foreach (var purchase in Model)
                        {
                            if (costsByCategories.ContainsKey(purchase.CategoryId))
                            {
                                costsByCategories[purchase.CategoryId].Value += purchase.UnitCost * purchase.Amount;
                            }
                            else
                            {
                                costsByCategories.Add(purchase.CategoryId, new CostsDataPoint {Color = purchase.Category.ColorForDiagram, Value = purchase.UnitCost * purchase.Amount, Name = purchase.Category.Name});
                            }
                        }

                    <text>
                        // Create the data table
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Category');
                        data.addColumn('number', 'Slices');

                        var options;
                        var colorsTabel = [];
                        var i = 0;

                        @{
                            foreach (var item in costsByCategories)
                            {
                                string name = item.Value.Name;
                                double value = item.Value.Value;
                                <text>
                                    data.addRow(['@name', parseFloat('@value')]);
                                    colorsTabel[i] = '@item.Value.Color';
                                    i++;
                                </text>
                            }
                        }
                           
                        

                        options = {
                            'width': 600,
                            'height': 400,
                            'colors': colorsTabel,
                            'chartArea': { left: 10, top: 0, width: '100%', height: '100%' },
                            'legend': { position: 'right', textStyle: { fontSize: 18 }, alignment: 'center' },
                            'titleTextStyle': { fontSize: 20, bold: false }
                        };

                        // Instantiate and draw the chart
                        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                        chart.draw(data, options);
                    </text>
                    }
               }
    }

</script>

CostsCalculator/Views/Shared/UserTitel.cshtml
@{
    string  userName = User.Identity.Name;
}
<div>Current user:@userName</div>

CostsCalculator/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>  
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    

    <title></title>
</head>
<body>
<div>
    @RenderBody()

    @Scripts.Render("~/bundles/jqueryval")
</div>
</body>
</html>

CostsCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
    @Scripts.Render("~/scripts/jquery-1.7.1.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/bundles/jquery")
    <!--стили jquery ui-->
    @Styles.Render("~/Content/themes/base/css")
    <!--сама библиотека jquey ui-->
    @Scripts.Render("~/bundles/jqueryui")

    <script type="text/javascript" src="~/Scripts/jscolor.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
   
</head>
<body>
<div id="header">
    <div class="title">
        <div>COSTS CALCULATOR</div>
        <div id="logOut">
            @Html.Partial("UserTitel")
            @Html.ActionLink("Log Out", "Logoff", "Account")
            @Html.ActionLink("Modify User Data", "ModificationUserData", "Account")
        </div>
</div>
</div>
<div id="body">
    <div id="menu">
        <div class="item">@Html.ActionLink("Home","Index","Purchase")</div>
        <div class="item">@Html.ActionLink("Categories", "GetAllCategories", "Category")</div>
        <div class="item">@Html.ActionLink("Purchases", "FirstListPurchases", "Purchase")</div>
    </div>
    <div id="content">
        @RenderBody()
        
        

        @RenderSection("scripts", required: false)
        <!--if browser doesn't create special field for date, than add datepicker-->
        <script type="text/javascript">
            $(function () {
                if (!Modernizr.inputtypes.date) {
                    $(function () {
                        $("input[type='date']")
                            .datepicker({ dateFormat: 'dd/mm/yy' })
                            .get(0).setAttribute("type", "text");
                    });
                }
            });
        </script>
    </div>
</div>
</body>
</html>


<script>
    function setTextColor(picker) {
        document.getElementsByTagName('body')[0].style.color = '#' + picker.toString();
    }
</script>